//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcPractice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Required(ErrorMessage = "Please Insert ID")]
        [DisplayName("Employee ID")]
        public int empId { get; set; }
        [Required(ErrorMessage ="Please Insert Name")]
        [DisplayName("Employee Name")]
        public string empName { get; set; }
        [Required(ErrorMessage = "Please Insert Salary")]
        [DisplayName("Employee Salary")]       
        public int empSalary { get; set; }
        [Required(ErrorMessage = "Please Insert Designation")]
        [DisplayName("Employee Designation")]
        public string empDesignation { get; set; }
        [Required(ErrorMessage = "Please Insert Department")]
        [DisplayName("Department ID")]
        public int depId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
